name: xplatform
description: A package to help make cross-platform UI development easier
version: 0.0.1
author: RMDY
homepage: https://github.com/digitalrmdy

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter